version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dhbw-cc2-backend
    volumes:
      - backend-node-modules:/app/node_modules
    environment:
      - ENDPOINT=https://eastus.api.cognitive.microsoft.com/
      - SUBSCRIPTION_KEY=value
      - PORT=3000
    networks:
      - app-network

  frontend:
    build: ./frontend/azure-summarizer
    container_name: dhbw-cc2-frontend
    networks:
      - app-network

  nginx-production-proxy:
    image: nginx:latest
    container_name: dhbw-cc2-nginx-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./challenges:/var/www/challenges
      - ./certs:/etc/letsencrypt
    ports:
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./challenges:/var/www/challenges
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  backend-node-modules:

networks:
  app-network:
